Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -8,25 +8,37 @@ set -o posix      # more strict failures in subshells
 # set -x          # enable debugging
 
 # Configure directories
-BUILD_DIR=$1
-CACHE_DIR=$2
-ENV_DIR=$3
-HEROKU_DIR=$BUILD_DIR/.heroku
-
-mkdir -p $HEROKU_DIR/mongo
+build_dir=$1
+cache_dir=$2
+env_dir=$3
+bp_dir=$(cd $(dirname $0); cd ..; pwd)
+heroku_dir=$build_dir/.heroku
+mkdir -p $heroku_dir/mongo
 warnings=$(mktemp)
 
-# Install mongodb to use mongo commands
-VERSION=5.0.24
-echo "Downloading and installing mongodb version $VERSION ..."
-BASE_FILE_NAME="mongodb-linux-x86_64-ubuntu1804-${VERSION}"
-download_url="https://fastdl.mongodb.org/linux/${BASE_FILE_NAME}.tgz"
-curl $download_url -s -o - | tar xzf - -C /tmp
+# Update MongoDB version to a later version (e.g., 5.0.0 or higher)
+mongo_version="5.0.24"
 
-# Move mongodb binaries into the app directory
-mv /tmp/${BASE_FILE_NAME}/* $HEROKU_DIR/mongo
-chmod +x $HEROKU_DIR/mongo/bin/*
+[[ $STACK = "heroku-16" ]] && os_id="ubuntu1604" || os_id="ubuntu2004"
 
-echo "Creating run-time environment"
-mkdir -p $BUILD_DIR/.profile.d
-echo "export PATH=\"\$HOME/.heroku/mongo/bin:\$PATH\"" > $BUILD_DIR/.profile.d/mongo.sh
+# Echo the os_id for debugging
+echo "Determined OS ID: $os_id"
+
+file_name="mongodb-linux-x86_64-${os_id}-${mongo_version}.tgz"
+folder_name=$(echo "$file_name" | sed 's/\.tgz$//')
+download_url="https://fastdl.mongodb.org/linux/${file_name}"
+
+# Download and extract MongoDB binaries
+curl -f -s -o /tmp/mongodb.tgz "${download_url}" || { echo "Download failed! Exiting."; exit 1; }
+tar xzf /tmp/mongodb.tgz -C /tmp || { echo "Extraction failed! Exiting."; exit 1; }
+
+# Move MongoDB binaries into the app directory
+mv "/tmp/${folder_name}"/* $heroku_dir/mongo
+chmod +x $heroku_dir/mongo/bin/*
+
+echo "-----> Creating runtime environment"
+mkdir -p $build_dir/.profile.d
+echo "export PATH=\"\$HOME/.heroku/mongo/bin:\$PATH\"" > $build_dir/.profile.d/mongo.sh
+
+# Additional debug information
+echo "MongoDB binaries installed. PATH updated."
